# A workflow to fetch and download the .whl file
name: Get Artifact Installed

on:
  workflow_run:
    workflows: ["Awesome Calculator CI build"]
    types:
      - completed

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with git actions
      uses: actions/checkout@v2

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: src/dist

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: awesome-calculator
        path: src/dist

    - name: Install WHL File
      run: |
        pip install src/dist/awesome-calculator/*.whl
