# GitHub CI build pipeline
name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    name: Create Artifacts

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install coverage
        pip install wheel
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Unit Tests and generate coverage report
      run: |
        cd src
        python -m unittest -v
        coverage run -m unittest
        coverage report
        coverage html
    
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: src/htmlcov
    
    - name: Run package creation
      run: |
        cd src
        python -m pip install --user --upgrade build
        python -m build
    
    - name: Build a WHL file
      run: |
        cd src
        python setup.py sdist bdist_wheel
    
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: awesome-calculator
        path: src/dist    
    
    - name: Commit and push the archived package
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Committing the archived package"
        git push
  
  
  install:
    name: Fetch and Install Artifact

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository with git actions
      uses: actions/checkout@v2

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: src/dist

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: awesome-calculator
        path: src/dist

    - name: Display structure after downloading
      run: ls -R
      working-directory: src/dist

    - name: Install WHL File
      run: |
        mkdir install_dir
        cp src/dist/awesome-calculator/dedreira_awesomecalculator-1.0.0-py3-none-any.whl install_dir/
        pip install install_dir/dedreira_awesomecalculator-1.0.0-py3-none-any.whl
